name: Development

on: [pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}
    
    strategy:
      matrix:
        os:
          - ubuntu
        
        ruby:
          - 3.0
          - 2.7
          - 2.6
        
        experimental: [false]
        env: [""]
        
        include:
          - os: ubuntu
            ruby: head
            experimental: true
    
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    
    - name: Rubocop
      timeout-minutes: 1
      run: ${{matrix.env}} bundle exec rubocop lib/ spec/

    - name: Run tests
      timeout-minutes: 5
      run: ${{matrix.env}} bundle exec rspec
      env:
        RMQ_HOST: localhost

    services:
      rabbitmq:
        image: 'rabbitmq:3.8.9-management'
        ports:
          - '5672:5672'
          - '15672:15672'
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest

